name: work_tracker
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_database: ^9.1.0
  firebase_messaging: ^12.0.1
  firebase_storage: ^10.3.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.8
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_sound: ^9.2.13
  just_audio: ^0.9.28
  syncfusion_flutter_pdfviewer: ^20.2.45-beta

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 19 # android min sdk min:16, default
  web:
    generate: false
  windows:
    generate: false

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: assets/images/splash.png
  branding: assets/images/branding.png
  branding_mode: bottom
  color_dark: "#000000"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/images/splash.png
  branding_dark: assets/images/branding.png
  android_12:
    image: assets/images/splash.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
    branding: assets/images/branding.png
    image_dark: assets/images/splash.png
    color_dark: "#000000"
    icon_background_color_dark: "#000000"
    branding_dark: assets/images/branding.png
  android: true
  ios: false
  web: false

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.otf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.otf
          weight: 900
          
# cloud_functions: ^3.3.3
# cupertino_icons: ^1.0.2
# firebase_app_check: ^0.0.6+18
