name: work_tracker
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  # cloud_firestore: ^3.4.3
  # cloud_functions: ^3.3.3
  cupertino_icons: ^1.0.2
  # firebase_app_check: ^0.0.6+18
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_database: ^9.1.0
  # firebase_messaging: ^12.0.1
  firebase_storage: ^10.3.4
  flutter:
    sdk: flutter
  # intl: ^0.17.0
  # path_provider: ^2.0.11
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.otf
          weight: 700
